"""empty message

Revision ID: b9b13faebbeb
Revises: a5cffa318ac2
Create Date: 2025-05-05 22:13:08.844059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b13faebbeb'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.Column('surface_water', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.Column('gravity', sa.String(length=250), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consumables', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=False),
    sa.Column('crew', sa.String(length=150), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=False),
    sa.Column('pilots', sa.String(length=150), nullable=False),
    sa.Column('MGLT', sa.Integer(), nullable=False),
    sa.Column('starship_class', sa.String(length=150), nullable=False),
    sa.Column('hyperdrive_rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=False),
    sa.Column('crew', sa.String(length=150), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=False),
    sa.Column('vehicle_class', sa.String(length=150), nullable=False),
    sa.Column('pilots', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('peoples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.Column('skin_color', sa.String(length=250), nullable=False),
    sa.Column('hair_color', sa.String(length=250), nullable=False),
    sa.Column('height', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=False),
    sa.Column('mass', sa.String(length=250), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classification', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('eye_colors', sa.String(length=150), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('skin_colors', sa.String(length=150), nullable=False),
    sa.Column('language', sa.String(length=150), nullable=False),
    sa.Column('hair_colors', sa.String(length=150), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=False),
    sa.Column('average_lifespan', sa.Integer(), nullable=False),
    sa.Column('average_height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['people'], ['peoples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('species')
    op.drop_table('peoples')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('starships')
    op.drop_table('planets')
    # ### end Alembic commands ###
